
const details = [
  {
    id: '1',
    name: 'Building Applications with React and Flux',
    image: 'https://pluralsight.imgix.net/course-images/react-flux-building-applications-v2.png',
    description: 'Get started with React, React Router, and Flux by building a real-world style date-driven application that manages Pluralsight author date. This course uses a modern client-side development stack including Node, Browserify, Gulp, and Bootstrap.',
    author:'Cory House',
    date: 'Aug 12, 2015',
    lengthTime: '5h 8m',
    gallery: [
      "https://2.pik.vn/20182c8c43fc-db6c-414d-a036-70a3d20bb2b9.png",
      "https://2.pik.vn/2018a08e8a3c-0c39-4f6e-b7cd-13eec7f86de9.png",
      "https://2.pik.vn/2018a68adb93-dc4c-4221-a428-2ca911bc4900.png",
      "https://2.pik.vn/2018ba36eb20-b4b6-4f52-8cbf-53d9f2cd7eb0.png",
      "https://2.pik.vn/2018949b6800-8f79-438c-8abc-3fac0a1397f2.png",
      "https://2.pik.vn/20180d726b81-c3ef-4b4e-ab56-0fcc35d171a5.png",
      "https://2.pik.vn/2018cbaec88a-6cd1-4821-99c5-dda73bfff0a2.png",
      "https://2.pik.vn/20184fa3e7c2-ad05-4541-b754-d0ec0840df58.png",
    ],
    content: "<p><b>Property Location</b> <br />With a stay at V Hotel Lavender, you'll be centrally located in Singapore, within a 10-minute drive of Singapore Flyer and Esplanade Theatres.  This hotel is 4.5 mi (7.3 km) from Chinatown Heritage Center and 5 mi (8.1 km) from National Orchid Garden.</p><p><b>Rooms</b> <br />Make yourself at home in one of the 888 air-conditioned rooms featuring refrigerators and LED televisions. Complimentary wireless Internet access keeps you connected, and cable programming is available for your entertainment. Private bathrooms with showers feature complimentary toiletries and hair dryers. Conveniences include safes and desks, as well as phones with free local calls.</p><p><b>Amenities</b> <br />Be sure to enjoy recreational amenities including an outdoor pool and a fitness center. Additional amenities at this hotel include complimentary wireless Internet access, gift shops/newsstands, and a hair salon.</p><p><b>Dining</b> <br />Grab a bite at 12-inch Pizzas and Record, a restaurant which features a bar and a garden view. You can also stay in and take advantage of the room service (during limited hours). Breakfast is available daily from 6:30 AM to 10:30 AM for a fee.</p><p><b>Business, Other Amenities</b> <br />Featured amenities include express check-in, express check-out, and dry cleaning/laundry services. Self parking (subject to charges) is available onsite.</p>",
  },
  {
    id: '2',
    name: 'Building Applications with React and Redux in ES6',
    image: 'https://pluralsight.imgix.net/course-images/react-boilerplate-building-scalable-apps-v1.jpg',
    description: 'Learn how to use Redux, React Router, and ES6 to build a real world app with React. Use Webpack, Babel, ESLint, npm scripts, Mocha, Enzyme, and more to build a rich, one step, custom React development environment and build process from the ground up.5',
    author: 'Cory House',
    date: 'Aug 12, 2015',
    lengthTime: '5h 8m',
    gallery: [
      "https://2.pik.vn/20182c8c43fc-db6c-414d-a036-70a3d20bb2b9.png",
      "https://2.pik.vn/2018a08e8a3c-0c39-4f6e-b7cd-13eec7f86de9.png",
      "https://2.pik.vn/2018a68adb93-dc4c-4221-a428-2ca911bc4900.png",
      "https://2.pik.vn/2018ba36eb20-b4b6-4f52-8cbf-53d9f2cd7eb0.png",
      "https://2.pik.vn/2018949b6800-8f79-438c-8abc-3fac0a1397f2.png",
      "https://2.pik.vn/20180d726b81-c3ef-4b4e-ab56-0fcc35d171a5.png",
      "https://2.pik.vn/2018cbaec88a-6cd1-4821-99c5-dda73bfff0a2.png",
      "https://2.pik.vn/20184fa3e7c2-ad05-4541-b754-d0ec0840df58.png",
    ],
    content: "<p><b>Property Location</b> <br />With a stay at V Hotel Lavender, you'll be centrally located in Singapore, within a 10-minute drive of Singapore Flyer and Esplanade Theatres.  This hotel is 4.5 mi (7.3 km) from Chinatown Heritage Center and 5 mi (8.1 km) from National Orchid Garden.</p><p><b>Rooms</b> <br />Make yourself at home in one of the 888 air-conditioned rooms featuring refrigerators and LED televisions. Complimentary wireless Internet access keeps you connected, and cable programming is available for your entertainment. Private bathrooms with showers feature complimentary toiletries and hair dryers. Conveniences include safes and desks, as well as phones with free local calls.</p><p><b>Amenities</b> <br />Be sure to enjoy recreational amenities including an outdoor pool and a fitness center. Additional amenities at this hotel include complimentary wireless Internet access, gift shops/newsstands, and a hair salon.</p><p><b>Dining</b> <br />Grab a bite at 12-inch Pizzas and Record, a restaurant which features a bar and a garden view. You can also stay in and take advantage of the room service (during limited hours). Breakfast is available daily from 6:30 AM to 10:30 AM for a fee.</p><p><b>Business, Other Amenities</b> <br />Featured amenities include express check-in, express check-out, and dry cleaning/laundry services. Self parking (subject to charges) is available onsite.</p>",
  },
  {
    id: '3',
    name: ' Building Scalable React Apps',
    image: 'https://pluralsight.imgix.net/course-images/react-redux-react-router-es6-v1.jpg',
    description: 'In this course, Building Scalable React Apps, you will remove the guesswork with the React-Boilerplate stack so that you can keep on delivering features, without needing to evolve your stack with every new addition.',
    author: 'Hendrik Swanepoel',
    date: 'Oct 27, 2016',
    lengthTime: '3h 48m',
    gallery: [
      "https://2.pik.vn/20182c8c43fc-db6c-414d-a036-70a3d20bb2b9.png",
      "https://2.pik.vn/2018a08e8a3c-0c39-4f6e-b7cd-13eec7f86de9.png",
      "https://2.pik.vn/2018a68adb93-dc4c-4221-a428-2ca911bc4900.png",
      "https://2.pik.vn/2018ba36eb20-b4b6-4f52-8cbf-53d9f2cd7eb0.png",
      "https://2.pik.vn/2018949b6800-8f79-438c-8abc-3fac0a1397f2.png",
      "https://2.pik.vn/20180d726b81-c3ef-4b4e-ab56-0fcc35d171a5.png",
      "https://2.pik.vn/2018cbaec88a-6cd1-4821-99c5-dda73bfff0a2.png",
      "https://2.pik.vn/20184fa3e7c2-ad05-4541-b754-d0ec0840df58.png",
    ],
    content: "<p><b>Property Location</b> <br />With a stay at V Hotel Lavender, you'll be centrally located in Singapore, within a 10-minute drive of Singapore Flyer and Esplanade Theatres.  This hotel is 4.5 mi (7.3 km) from Chinatown Heritage Center and 5 mi (8.1 km) from National Orchid Garden.</p><p><b>Rooms</b> <br />Make yourself at home in one of the 888 air-conditioned rooms featuring refrigerators and LED televisions. Complimentary wireless Internet access keeps you connected, and cable programming is available for your entertainment. Private bathrooms with showers feature complimentary toiletries and hair dryers. Conveniences include safes and desks, as well as phones with free local calls.</p><p><b>Amenities</b> <br />Be sure to enjoy recreational amenities including an outdoor pool and a fitness center. Additional amenities at this hotel include complimentary wireless Internet access, gift shops/newsstands, and a hair salon.</p><p><b>Dining</b> <br />Grab a bite at 12-inch Pizzas and Record, a restaurant which features a bar and a garden view. You can also stay in and take advantage of the room service (during limited hours). Breakfast is available daily from 6:30 AM to 10:30 AM for a fee.</p><p><b>Business, Other Amenities</b> <br />Featured amenities include express check-in, express check-out, and dry cleaning/laundry services. Self parking (subject to charges) is available onsite.</p>",
  },
  {
    id: '4',
    name: 'Styling React Components',
    image: 'https://pluralsight.imgix.net/course-images/react-styling-components-v1.jpg',
    description: 'React has changed the way that people think about writing UIs. It has encouraged a community where ideas about how to style UIs have changed as well. There are now several compelling options for how to style your React components. Some are more traditional, some are more progressive.',
    author: 'Jake Trent',
    date: 'Jan 5, 2016',
    lengthTime: '1h 29m',
    gallery: [
      "https://2.pik.vn/20182c8c43fc-db6c-414d-a036-70a3d20bb2b9.png",
      "https://2.pik.vn/2018a08e8a3c-0c39-4f6e-b7cd-13eec7f86de9.png",
      "https://2.pik.vn/2018a68adb93-dc4c-4221-a428-2ca911bc4900.png",
      "https://2.pik.vn/2018ba36eb20-b4b6-4f52-8cbf-53d9f2cd7eb0.png",
      "https://2.pik.vn/2018949b6800-8f79-438c-8abc-3fac0a1397f2.png",
      "https://2.pik.vn/20180d726b81-c3ef-4b4e-ab56-0fcc35d171a5.png",
      "https://2.pik.vn/2018cbaec88a-6cd1-4821-99c5-dda73bfff0a2.png",
      "https://2.pik.vn/20184fa3e7c2-ad05-4541-b754-d0ec0840df58.png",
    ],
    content: "<p><b>Property Location</b> <br />With a stay at V Hotel Lavender, you'll be centrally located in Singapore, within a 10-minute drive of Singapore Flyer and Esplanade Theatres.  This hotel is 4.5 mi (7.3 km) from Chinatown Heritage Center and 5 mi (8.1 km) from National Orchid Garden.</p><p><b>Rooms</b> <br />Make yourself at home in one of the 888 air-conditioned rooms featuring refrigerators and LED televisions. Complimentary wireless Internet access keeps you connected, and cable programming is available for your entertainment. Private bathrooms with showers feature complimentary toiletries and hair dryers. Conveniences include safes and desks, as well as phones with free local calls.</p><p><b>Amenities</b> <br />Be sure to enjoy recreational amenities including an outdoor pool and a fitness center. Additional amenities at this hotel include complimentary wireless Internet access, gift shops/newsstands, and a hair salon.</p><p><b>Dining</b> <br />Grab a bite at 12-inch Pizzas and Record, a restaurant which features a bar and a garden view. You can also stay in and take advantage of the room service (during limited hours). Breakfast is available daily from 6:30 AM to 10:30 AM for a fee.</p><p><b>Business, Other Amenities</b> <br />Featured amenities include express check-in, express check-out, and dry cleaning/laundry services. Self parking (subject to charges) is available onsite.</p>",
  },
  {
    id: '5',
    name: 'Testing React Applications with Jest',
    image: 'https://pluralsight.imgix.net/course-images/testing-react-applications-jest-v2.png',
    description: 'At the heart of building durable and reliable React applications is a solid understanding of testing, starting with Jest. In this course, Testing React Applications with Jest, you will learn everything you need to do to create solid tests for your React components and applications. First, you’ll learn how to install Jest on any machine',
    author: 'Daniel Stern',
    date: 'May 11, 2018',
    lengthTime: '3h 36m',
    gallery: [
      "https://2.pik.vn/20182c8c43fc-db6c-414d-a036-70a3d20bb2b9.png",
      "https://2.pik.vn/2018a08e8a3c-0c39-4f6e-b7cd-13eec7f86de9.png",
      "https://2.pik.vn/2018a68adb93-dc4c-4221-a428-2ca911bc4900.png",
      "https://2.pik.vn/2018ba36eb20-b4b6-4f52-8cbf-53d9f2cd7eb0.png",
      "https://2.pik.vn/2018949b6800-8f79-438c-8abc-3fac0a1397f2.png",
      "https://2.pik.vn/20180d726b81-c3ef-4b4e-ab56-0fcc35d171a5.png",
      "https://2.pik.vn/2018cbaec88a-6cd1-4821-99c5-dda73bfff0a2.png",
      "https://2.pik.vn/20184fa3e7c2-ad05-4541-b754-d0ec0840df58.png",
    ],
    content: "<p><b>Property Location</b> <br />With a stay at V Hotel Lavender, you'll be centrally located in Singapore, within a 10-minute drive of Singapore Flyer and Esplanade Theatres.  This hotel is 4.5 mi (7.3 km) from Chinatown Heritage Center and 5 mi (8.1 km) from National Orchid Garden.</p><p><b>Rooms</b> <br />Make yourself at home in one of the 888 air-conditioned rooms featuring refrigerators and LED televisions. Complimentary wireless Internet access keeps you connected, and cable programming is available for your entertainment. Private bathrooms with showers feature complimentary toiletries and hair dryers. Conveniences include safes and desks, as well as phones with free local calls.</p><p><b>Amenities</b> <br />Be sure to enjoy recreational amenities including an outdoor pool and a fitness center. Additional amenities at this hotel include complimentary wireless Internet access, gift shops/newsstands, and a hair salon.</p><p><b>Dining</b> <br />Grab a bite at 12-inch Pizzas and Record, a restaurant which features a bar and a garden view. You can also stay in and take advantage of the room service (during limited hours). Breakfast is available daily from 6:30 AM to 10:30 AM for a fee.</p><p><b>Business, Other Amenities</b> <br />Featured amenities include express check-in, express check-out, and dry cleaning/laundry services. Self parking (subject to charges) is available onsite.</p>",
  },
  {
    id: '6',
    name: 'Building a Full-Stack App with React and Express',
    image: 'https://pluralsight.imgix.net/course-images/react-express-full-stack-app-build-v1.jpg',
    description: 'In this course, well build a full-featured web application which emphasizes lighting-fast load times and live updates. Well learn how to use React.js to build a front-end web application, and use Browserify and Gulp to load the app isomorphically in Node.js',
    author: 'Daniel Stern',
    date: 'Aug 17, 2015',
    lengthTime: '3h 24m',
    gallery: [
      "https://2.pik.vn/20182c8c43fc-db6c-414d-a036-70a3d20bb2b9.png",
      "https://2.pik.vn/2018a08e8a3c-0c39-4f6e-b7cd-13eec7f86de9.png",
      "https://2.pik.vn/2018a68adb93-dc4c-4221-a428-2ca911bc4900.png",
      "https://2.pik.vn/2018ba36eb20-b4b6-4f52-8cbf-53d9f2cd7eb0.png",
      "https://2.pik.vn/2018949b6800-8f79-438c-8abc-3fac0a1397f2.png",
      "https://2.pik.vn/20180d726b81-c3ef-4b4e-ab56-0fcc35d171a5.png",
      "https://2.pik.vn/2018cbaec88a-6cd1-4821-99c5-dda73bfff0a2.png",
      "https://2.pik.vn/20184fa3e7c2-ad05-4541-b754-d0ec0840df58.png",
    ],
    content: "<p><b>Property Location</b> <br />With a stay at V Hotel Lavender, you'll be centrally located in Singapore, within a 10-minute drive of Singapore Flyer and Esplanade Theatres.  This hotel is 4.5 mi (7.3 km) from Chinatown Heritage Center and 5 mi (8.1 km) from National Orchid Garden.</p><p><b>Rooms</b> <br />Make yourself at home in one of the 888 air-conditioned rooms featuring refrigerators and LED televisions. Complimentary wireless Internet access keeps you connected, and cable programming is available for your entertainment. Private bathrooms with showers feature complimentary toiletries and hair dryers. Conveniences include safes and desks, as well as phones with free local calls.</p><p><b>Amenities</b> <br />Be sure to enjoy recreational amenities including an outdoor pool and a fitness center. Additional amenities at this hotel include complimentary wireless Internet access, gift shops/newsstands, and a hair salon.</p><p><b>Dining</b> <br />Grab a bite at 12-inch Pizzas and Record, a restaurant which features a bar and a garden view. You can also stay in and take advantage of the room service (during limited hours). Breakfast is available daily from 6:30 AM to 10:30 AM for a fee.</p><p><b>Business, Other Amenities</b> <br />Featured amenities include express check-in, express check-out, and dry cleaning/laundry services. Self parking (subject to charges) is available onsite.</p>",
  },
];


export default details;



