
const details = [
  {
    id: 'pid001',
    name: 'CSS3',
    description: "Cascading Style Sheets (CSS) is a stylesheet language used to describe the presentation of a document written in HTML or XML (including XML dialects such as SVG, MathML or XHTML). CSS describes how elements should be rendered on screen, on paper, in speech, or on other media.",
    image: 'https://2.pik.vn/20188b022366-7c2b-4a02-8e48-e187c65c6ce2.png',
    gallery: [
      "https://2.pik.vn/20182c8c43fc-db6c-414d-a036-70a3d20bb2b9.png",
      "https://2.pik.vn/2018a08e8a3c-0c39-4f6e-b7cd-13eec7f86de9.png",
      "https://2.pik.vn/2018a68adb93-dc4c-4221-a428-2ca911bc4900.png",
      "https://2.pik.vn/2018ba36eb20-b4b6-4f52-8cbf-53d9f2cd7eb0.png",
      "https://2.pik.vn/2018949b6800-8f79-438c-8abc-3fac0a1397f2.png",
      "https://2.pik.vn/20180d726b81-c3ef-4b4e-ab56-0fcc35d171a5.png",
      "https://2.pik.vn/2018cbaec88a-6cd1-4821-99c5-dda73bfff0a2.png",
      "https://2.pik.vn/20184fa3e7c2-ad05-4541-b754-d0ec0840df58.png",
    ],
    content: "<p><b>Property Location</b> <br />With a stay at V Hotel Lavender, you'll be centrally located in Singapore, within a 10-minute drive of Singapore Flyer and Esplanade Theatres.  This hotel is 4.5 mi (7.3 km) from Chinatown Heritage Center and 5 mi (8.1 km) from National Orchid Garden.</p><p><b>Rooms</b> <br />Make yourself at home in one of the 888 air-conditioned rooms featuring refrigerators and LED televisions. Complimentary wireless Internet access keeps you connected, and cable programming is available for your entertainment. Private bathrooms with showers feature complimentary toiletries and hair dryers. Conveniences include safes and desks, as well as phones with free local calls.</p><p><b>Amenities</b> <br />Be sure to enjoy recreational amenities including an outdoor pool and a fitness center. Additional amenities at this hotel include complimentary wireless Internet access, gift shops/newsstands, and a hair salon.</p><p><b>Dining</b> <br />Grab a bite at 12-inch Pizzas and Record, a restaurant which features a bar and a garden view. You can also stay in and take advantage of the room service (during limited hours). Breakfast is available daily from 6:30 AM to 10:30 AM for a fee.</p><p><b>Business, Other Amenities</b> <br />Featured amenities include express check-in, express check-out, and dry cleaning/laundry services. Self parking (subject to charges) is available onsite.</p>",
    dateCreate: '17-11-1993',
  },
  {
    id: 'pid002',
    name: 'HTML 5',
    description: "HTML5 is the latest evolution of the standard that defines HTML. The term represents two different concepts. It is a new version of the language HTML, with new elements, attributes, and behaviors, and a larger set of technologies that allows the building of more diverse and powerful Web sites and applications. This set is sometimes called HTML5 & friends and often shortened to just HTML5.",
    image: 'https://2.pik.vn/2018d59aa8b0-3437-47e9-9f8b-27ff8fcd52d0.png',
    gallery: [
      "https://2.pik.vn/20182c8c43fc-db6c-414d-a036-70a3d20bb2b9.png",
      "https://2.pik.vn/2018a08e8a3c-0c39-4f6e-b7cd-13eec7f86de9.png",
      "https://2.pik.vn/2018a68adb93-dc4c-4221-a428-2ca911bc4900.png",
      "https://2.pik.vn/2018ba36eb20-b4b6-4f52-8cbf-53d9f2cd7eb0.png",
      "https://2.pik.vn/2018949b6800-8f79-438c-8abc-3fac0a1397f2.png",
      "https://2.pik.vn/20180d726b81-c3ef-4b4e-ab56-0fcc35d171a5.png",
      "https://2.pik.vn/2018cbaec88a-6cd1-4821-99c5-dda73bfff0a2.png",
      "https://2.pik.vn/20184fa3e7c2-ad05-4541-b754-d0ec0840df58.png",
    ],
    content: "<p><b>Property Location</b> <br />With a stay at V Hotel Lavender, you'll be centrally located in Singapore, within a 10-minute drive of Singapore Flyer and Esplanade Theatres.  This hotel is 4.5 mi (7.3 km) from Chinatown Heritage Center and 5 mi (8.1 km) from National Orchid Garden.</p><p><b>Rooms</b> <br />Make yourself at home in one of the 888 air-conditioned rooms featuring refrigerators and LED televisions. Complimentary wireless Internet access keeps you connected, and cable programming is available for your entertainment. Private bathrooms with showers feature complimentary toiletries and hair dryers. Conveniences include safes and desks, as well as phones with free local calls.</p><p><b>Amenities</b> <br />Be sure to enjoy recreational amenities including an outdoor pool and a fitness center. Additional amenities at this hotel include complimentary wireless Internet access, gift shops/newsstands, and a hair salon.</p><p><b>Dining</b> <br />Grab a bite at 12-inch Pizzas and Record, a restaurant which features a bar and a garden view. You can also stay in and take advantage of the room service (during limited hours). Breakfast is available daily from 6:30 AM to 10:30 AM for a fee.</p><p><b>Business, Other Amenities</b> <br />Featured amenities include express check-in, express check-out, and dry cleaning/laundry services. Self parking (subject to charges) is available onsite.</p>",
    dateCreate: '17-11-1993',
  },
  {
    id: 'pid003',
    name: 'Javascript',
    description: "JavaScript is a programming language that adds interactivity to your website (for example: games, responses when buttons are pressed or data entered in forms, dynamic styling, animation). This article helps you get started with this exciting language and gives you an idea of what is possible.",
    image: 'https://2.pik.vn/2018d6a26dfd-666f-43da-8593-0e4f48cabb52.png',
    gallery: [
      "https://2.pik.vn/20182c8c43fc-db6c-414d-a036-70a3d20bb2b9.png",
      "https://2.pik.vn/2018a08e8a3c-0c39-4f6e-b7cd-13eec7f86de9.png",
      "https://2.pik.vn/2018a68adb93-dc4c-4221-a428-2ca911bc4900.png",
      "https://2.pik.vn/2018ba36eb20-b4b6-4f52-8cbf-53d9f2cd7eb0.png",
      "https://2.pik.vn/2018949b6800-8f79-438c-8abc-3fac0a1397f2.png",
      "https://2.pik.vn/20180d726b81-c3ef-4b4e-ab56-0fcc35d171a5.png",
      "https://2.pik.vn/2018cbaec88a-6cd1-4821-99c5-dda73bfff0a2.png",
      "https://2.pik.vn/20184fa3e7c2-ad05-4541-b754-d0ec0840df58.png",
    ],
    content: "<p><b>Property Location</b> <br />With a stay at V Hotel Lavender, you'll be centrally located in Singapore, within a 10-minute drive of Singapore Flyer and Esplanade Theatres.  This hotel is 4.5 mi (7.3 km) from Chinatown Heritage Center and 5 mi (8.1 km) from National Orchid Garden.</p><p><b>Rooms</b> <br />Make yourself at home in one of the 888 air-conditioned rooms featuring refrigerators and LED televisions. Complimentary wireless Internet access keeps you connected, and cable programming is available for your entertainment. Private bathrooms with showers feature complimentary toiletries and hair dryers. Conveniences include safes and desks, as well as phones with free local calls.</p><p><b>Amenities</b> <br />Be sure to enjoy recreational amenities including an outdoor pool and a fitness center. Additional amenities at this hotel include complimentary wireless Internet access, gift shops/newsstands, and a hair salon.</p><p><b>Dining</b> <br />Grab a bite at 12-inch Pizzas and Record, a restaurant which features a bar and a garden view. You can also stay in and take advantage of the room service (during limited hours). Breakfast is available daily from 6:30 AM to 10:30 AM for a fee.</p><p><b>Business, Other Amenities</b> <br />Featured amenities include express check-in, express check-out, and dry cleaning/laundry services. Self parking (subject to charges) is available onsite.</p>",
    dateCreate: '17-11-1993',
  },
  {
    id: 'pid004',
    name: 'React JS',
    description: "React makes it painless to create interactive UIs. Design simple views for each state in your application, and React will efficiently update and render just the right components when your data changes.",
    image: 'https://2.pik.vn/201868dbc23b-952a-4358-b297-adbeb414a0a6.png',
    gallery: [
      "https://2.pik.vn/20182c8c43fc-db6c-414d-a036-70a3d20bb2b9.png",
      "https://2.pik.vn/2018a08e8a3c-0c39-4f6e-b7cd-13eec7f86de9.png",
      "https://2.pik.vn/2018a68adb93-dc4c-4221-a428-2ca911bc4900.png",
      "https://2.pik.vn/2018ba36eb20-b4b6-4f52-8cbf-53d9f2cd7eb0.png",
      "https://2.pik.vn/2018949b6800-8f79-438c-8abc-3fac0a1397f2.png",
      "https://2.pik.vn/20180d726b81-c3ef-4b4e-ab56-0fcc35d171a5.png",
      "https://2.pik.vn/2018cbaec88a-6cd1-4821-99c5-dda73bfff0a2.png",
      "https://2.pik.vn/20184fa3e7c2-ad05-4541-b754-d0ec0840df58.png",
    ],
    content: "<p><b>Property Location</b> <br />With a stay at V Hotel Lavender, you'll be centrally located in Singapore, within a 10-minute drive of Singapore Flyer and Esplanade Theatres.  This hotel is 4.5 mi (7.3 km) from Chinatown Heritage Center and 5 mi (8.1 km) from National Orchid Garden.</p><p><b>Rooms</b> <br />Make yourself at home in one of the 888 air-conditioned rooms featuring refrigerators and LED televisions. Complimentary wireless Internet access keeps you connected, and cable programming is available for your entertainment. Private bathrooms with showers feature complimentary toiletries and hair dryers. Conveniences include safes and desks, as well as phones with free local calls.</p><p><b>Amenities</b> <br />Be sure to enjoy recreational amenities including an outdoor pool and a fitness center. Additional amenities at this hotel include complimentary wireless Internet access, gift shops/newsstands, and a hair salon.</p><p><b>Dining</b> <br />Grab a bite at 12-inch Pizzas and Record, a restaurant which features a bar and a garden view. You can also stay in and take advantage of the room service (during limited hours). Breakfast is available daily from 6:30 AM to 10:30 AM for a fee.</p><p><b>Business, Other Amenities</b> <br />Featured amenities include express check-in, express check-out, and dry cleaning/laundry services. Self parking (subject to charges) is available onsite.</p>",
    dateCreate: '17-11-1993',
  },
  {
    id: 'pid005',
    name: 'Vue JS',
    description: "Vue (pronounced /vjuː/, like view) is a progressive framework for building user interfaces. Unlike other monolithic frameworks, Vue is designed from the ground up to be incrementally adoptable. The core library is focused on the view layer only, and is easy to pick up and integrate with other libraries or existing projects. On the other hand, Vue is also perfectly capable of powering sophisticated Single-Page Applications when used in combination with modern tooling and supporting libraries.",
    image: 'https://2.pik.vn/201886840e86-ea9d-4922-b6a8-56400fffbe0f.png',
    gallery: [
      "https://2.pik.vn/20182c8c43fc-db6c-414d-a036-70a3d20bb2b9.png",
      "https://2.pik.vn/2018a08e8a3c-0c39-4f6e-b7cd-13eec7f86de9.png",
      "https://2.pik.vn/2018a68adb93-dc4c-4221-a428-2ca911bc4900.png",
      "https://2.pik.vn/2018ba36eb20-b4b6-4f52-8cbf-53d9f2cd7eb0.png",
      "https://2.pik.vn/2018949b6800-8f79-438c-8abc-3fac0a1397f2.png",
      "https://2.pik.vn/20180d726b81-c3ef-4b4e-ab56-0fcc35d171a5.png",
      "https://2.pik.vn/2018cbaec88a-6cd1-4821-99c5-dda73bfff0a2.png",
      "https://2.pik.vn/20184fa3e7c2-ad05-4541-b754-d0ec0840df58.png",
    ],
    content: "<p><b>Property Location</b> <br />With a stay at V Hotel Lavender, you'll be centrally located in Singapore, within a 10-minute drive of Singapore Flyer and Esplanade Theatres.  This hotel is 4.5 mi (7.3 km) from Chinatown Heritage Center and 5 mi (8.1 km) from National Orchid Garden.</p><p><b>Rooms</b> <br />Make yourself at home in one of the 888 air-conditioned rooms featuring refrigerators and LED televisions. Complimentary wireless Internet access keeps you connected, and cable programming is available for your entertainment. Private bathrooms with showers feature complimentary toiletries and hair dryers. Conveniences include safes and desks, as well as phones with free local calls.</p><p><b>Amenities</b> <br />Be sure to enjoy recreational amenities including an outdoor pool and a fitness center. Additional amenities at this hotel include complimentary wireless Internet access, gift shops/newsstands, and a hair salon.</p><p><b>Dining</b> <br />Grab a bite at 12-inch Pizzas and Record, a restaurant which features a bar and a garden view. You can also stay in and take advantage of the room service (during limited hours). Breakfast is available daily from 6:30 AM to 10:30 AM for a fee.</p><p><b>Business, Other Amenities</b> <br />Featured amenities include express check-in, express check-out, and dry cleaning/laundry services. Self parking (subject to charges) is available onsite.</p>",
    dateCreate: '17-11-1993',
  },
  {
    id: 'pid006',
    name: 'Webpack',
    description: "At its core, webpack is a static module bundler for modern JavaScript applications. When webpack processes your application, it internally builds a dependency graph which maps every module your project needs and generates one or more bundles.",
    image: 'https://2.pik.vn/20182c561564-82a4-4a13-99ed-8074effd1422.png',
    gallery: [
      "https://2.pik.vn/20182c8c43fc-db6c-414d-a036-70a3d20bb2b9.png",
      "https://2.pik.vn/2018a08e8a3c-0c39-4f6e-b7cd-13eec7f86de9.png",
      "https://2.pik.vn/2018a68adb93-dc4c-4221-a428-2ca911bc4900.png",
      "https://2.pik.vn/2018ba36eb20-b4b6-4f52-8cbf-53d9f2cd7eb0.png",
      "https://2.pik.vn/2018949b6800-8f79-438c-8abc-3fac0a1397f2.png",
      "https://2.pik.vn/20180d726b81-c3ef-4b4e-ab56-0fcc35d171a5.png",
      "https://2.pik.vn/2018cbaec88a-6cd1-4821-99c5-dda73bfff0a2.png",
      "https://2.pik.vn/20184fa3e7c2-ad05-4541-b754-d0ec0840df58.png",
    ],
    content: "<p><b>Property Location</b> <br />With a stay at V Hotel Lavender, you'll be centrally located in Singapore, within a 10-minute drive of Singapore Flyer and Esplanade Theatres.  This hotel is 4.5 mi (7.3 km) from Chinatown Heritage Center and 5 mi (8.1 km) from National Orchid Garden.</p><p><b>Rooms</b> <br />Make yourself at home in one of the 888 air-conditioned rooms featuring refrigerators and LED televisions. Complimentary wireless Internet access keeps you connected, and cable programming is available for your entertainment. Private bathrooms with showers feature complimentary toiletries and hair dryers. Conveniences include safes and desks, as well as phones with free local calls.</p><p><b>Amenities</b> <br />Be sure to enjoy recreational amenities including an outdoor pool and a fitness center. Additional amenities at this hotel include complimentary wireless Internet access, gift shops/newsstands, and a hair salon.</p><p><b>Dining</b> <br />Grab a bite at 12-inch Pizzas and Record, a restaurant which features a bar and a garden view. You can also stay in and take advantage of the room service (during limited hours). Breakfast is available daily from 6:30 AM to 10:30 AM for a fee.</p><p><b>Business, Other Amenities</b> <br />Featured amenities include express check-in, express check-out, and dry cleaning/laundry services. Self parking (subject to charges) is available onsite.</p>",
    dateCreate: '17-11-1993',
  },
  {
    id: 'pid007',
    name: 'Gulp',
    description: "Gulp allows you to use existing JavaScript knowledge to write gulpfiles or to use your experience with gulpfiles to write plain JavaScript. Although a few utilities are provided to simplify working with the filesystem and command line, everything else you write is pure JavaScript.",
    image: 'https://2.pik.vn/20188a7bea04-ec23-4845-a2b0-3762a1b50196.png',
    gallery: [
      "https://2.pik.vn/20182c8c43fc-db6c-414d-a036-70a3d20bb2b9.png",
      "https://2.pik.vn/2018a08e8a3c-0c39-4f6e-b7cd-13eec7f86de9.png",
      "https://2.pik.vn/2018a68adb93-dc4c-4221-a428-2ca911bc4900.png",
      "https://2.pik.vn/2018ba36eb20-b4b6-4f52-8cbf-53d9f2cd7eb0.png",
      "https://2.pik.vn/2018949b6800-8f79-438c-8abc-3fac0a1397f2.png",
      "https://2.pik.vn/20180d726b81-c3ef-4b4e-ab56-0fcc35d171a5.png",
      "https://2.pik.vn/2018cbaec88a-6cd1-4821-99c5-dda73bfff0a2.png",
      "https://2.pik.vn/20184fa3e7c2-ad05-4541-b754-d0ec0840df58.png",
    ],
    content: "<p><b>Property Location</b> <br />With a stay at V Hotel Lavender, you'll be centrally located in Singapore, within a 10-minute drive of Singapore Flyer and Esplanade Theatres.  This hotel is 4.5 mi (7.3 km) from Chinatown Heritage Center and 5 mi (8.1 km) from National Orchid Garden.</p><p><b>Rooms</b> <br />Make yourself at home in one of the 888 air-conditioned rooms featuring refrigerators and LED televisions. Complimentary wireless Internet access keeps you connected, and cable programming is available for your entertainment. Private bathrooms with showers feature complimentary toiletries and hair dryers. Conveniences include safes and desks, as well as phones with free local calls.</p><p><b>Amenities</b> <br />Be sure to enjoy recreational amenities including an outdoor pool and a fitness center. Additional amenities at this hotel include complimentary wireless Internet access, gift shops/newsstands, and a hair salon.</p><p><b>Dining</b> <br />Grab a bite at 12-inch Pizzas and Record, a restaurant which features a bar and a garden view. You can also stay in and take advantage of the room service (during limited hours). Breakfast is available daily from 6:30 AM to 10:30 AM for a fee.</p><p><b>Business, Other Amenities</b> <br />Featured amenities include express check-in, express check-out, and dry cleaning/laundry services. Self parking (subject to charges) is available onsite.</p>",
    dateCreate: '17-11-1993',
  },
  {
    id: 'pid008',
    name: 'Git',
    description: "Git is a free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency. Git is easy to learn and has a tiny footprint with lightning fast performance. It outclasses SCM tools like Subversion, CVS, Perforce, and ClearCase with features like cheap local branching, convenient staging areas, and multiple workflows.",
    image: 'https://2.pik.vn/2018522ad637-dcc3-47ca-8e5b-2b1b0ddea418.png',
    gallery: [
      "https://2.pik.vn/20182c8c43fc-db6c-414d-a036-70a3d20bb2b9.png",
      "https://2.pik.vn/2018a08e8a3c-0c39-4f6e-b7cd-13eec7f86de9.png",
      "https://2.pik.vn/2018a68adb93-dc4c-4221-a428-2ca911bc4900.png",
      "https://2.pik.vn/2018ba36eb20-b4b6-4f52-8cbf-53d9f2cd7eb0.png",
      "https://2.pik.vn/2018949b6800-8f79-438c-8abc-3fac0a1397f2.png",
      "https://2.pik.vn/20180d726b81-c3ef-4b4e-ab56-0fcc35d171a5.png",
      "https://2.pik.vn/2018cbaec88a-6cd1-4821-99c5-dda73bfff0a2.png",
      "https://2.pik.vn/20184fa3e7c2-ad05-4541-b754-d0ec0840df58.png",
    ],
    content: "<p><b>Property Location</b> <br />With a stay at V Hotel Lavender, you'll be centrally located in Singapore, within a 10-minute drive of Singapore Flyer and Esplanade Theatres.  This hotel is 4.5 mi (7.3 km) from Chinatown Heritage Center and 5 mi (8.1 km) from National Orchid Garden.</p><p><b>Rooms</b> <br />Make yourself at home in one of the 888 air-conditioned rooms featuring refrigerators and LED televisions. Complimentary wireless Internet access keeps you connected, and cable programming is available for your entertainment. Private bathrooms with showers feature complimentary toiletries and hair dryers. Conveniences include safes and desks, as well as phones with free local calls.</p><p><b>Amenities</b> <br />Be sure to enjoy recreational amenities including an outdoor pool and a fitness center. Additional amenities at this hotel include complimentary wireless Internet access, gift shops/newsstands, and a hair salon.</p><p><b>Dining</b> <br />Grab a bite at 12-inch Pizzas and Record, a restaurant which features a bar and a garden view. You can also stay in and take advantage of the room service (during limited hours). Breakfast is available daily from 6:30 AM to 10:30 AM for a fee.</p><p><b>Business, Other Amenities</b> <br />Featured amenities include express check-in, express check-out, and dry cleaning/laundry services. Self parking (subject to charges) is available onsite.</p>",
    dateCreate: '17-11-1993',
  },
]

export default details;